package demo.saga.order.domain

enum class OrderStatus {
    CREATED,
    HOLDING,
    HELD,
    UNHOLDING,
    UNHELD,
    CHECKING,
    CHECKED,
    ORDERING,
    ORDERED,
    CANCELING_WAREHOUSE,
    CANCELED_WAREHOUSE,
    CAPTURING,
    CAPTURED,
    SUCCESS_NOTIFYING,
    SUCCESS_NOTIFIED,
    CANCEL_NOTIFYING,
    CANCEL_NOTIFIED,
    PAID_AND_DISPATCHED,
    CANCELLED,
    MANUAL_HANDLING
}
